// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMApi.dbcontext;

#nullable disable

namespace SMApi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250801114454_stringToDatetimeCast")]
    partial class stringToDatetimeCast
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMApi.Models.Comments", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentId"));

                    b.Property<string>("commentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("postId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("commentId");

                    b.HasIndex("postId");

                    b.HasIndex("userId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("SMApi.Models.Likes", b =>
                {
                    b.Property<int>("likeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("likeId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("sMUsersuserId")
                        .HasColumnType("int");

                    b.Property<int>("targetId")
                        .HasColumnType("int");

                    b.Property<string>("targetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("likeId");

                    b.HasIndex("sMUsersuserId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("SMApi.Models.Posts", b =>
                {
                    b.Property<int>("postId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("postId"));

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("sMUsersuserId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("postId");

                    b.HasIndex("sMUsersuserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("SMApi.Models.SMUser", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("SMUser");
                });

            modelBuilder.Entity("SMApi.Models.UserSecurity", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("tokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("verificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("UserSecurity");
                });

            modelBuilder.Entity("SMApi.Models.Comments", b =>
                {
                    b.HasOne("SMApi.Models.Posts", "post")
                        .WithMany()
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMApi.Models.SMUser", "smusers")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("post");

                    b.Navigation("smusers");
                });

            modelBuilder.Entity("SMApi.Models.Likes", b =>
                {
                    b.HasOne("SMApi.Models.SMUser", "sMUsers")
                        .WithMany()
                        .HasForeignKey("sMUsersuserId");

                    b.Navigation("sMUsers");
                });

            modelBuilder.Entity("SMApi.Models.Posts", b =>
                {
                    b.HasOne("SMApi.Models.SMUser", "sMUsers")
                        .WithMany()
                        .HasForeignKey("sMUsersuserId");

                    b.Navigation("sMUsers");
                });

            modelBuilder.Entity("SMApi.Models.UserSecurity", b =>
                {
                    b.HasOne("SMApi.Models.SMUser", "sMUser")
                        .WithOne("userSecurity")
                        .HasForeignKey("SMApi.Models.UserSecurity", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sMUser");
                });

            modelBuilder.Entity("SMApi.Models.SMUser", b =>
                {
                    b.Navigation("userSecurity");
                });
#pragma warning restore 612, 618
        }
    }
}
